- name: Find all .env.template files in the project
  ansible.builtin.find:
    paths: "{{ APP_PATH }}"
    patterns: "*.env.template"
    recurse: yes
  register: template_files

- name: Show APP_PATH
  ansible.builtin.debug:
    var: APP_PATH

- name: List contents of APP_PATH
  ansible.builtin.command: ls -la "{{ APP_PATH }}"
  register: ls_result

- name: Show contents of APP_PATH
  ansible.builtin.debug:
    var: ls_result.stdout

- name: Debug print found template files
  ansible.builtin.debug:
    var: template_files.files

- name: Generate .env files from found templates
  ansible.builtin.template:
    src: "{{ item.path }}"
    dest: "{{ item.path | regex_replace('.env.template$', '.env') }}"
  loop: "{{ template_files.files }}"
  vars:
    secrets: "{{ secrets }}"
  notify: Create .env files
