- name: Ensure the git directory exists
  ansible.builtin.file:
    path: "{{ APP_PATH }}"
    state: directory
    mode: "0755"

- name: Check if .git directory exists
  ansible.builtin.stat:
    path: "{{ APP_PATH }}/.git"
  register: git_directory

- name: Clone the repository if it does not exist
  ansible.builtin.git:
    repo: "git@github.com:{{ GITHUB_REPO }}.git"
    dest: "{{ APP_PATH }}"
    version: main
  when: not git_directory.stat.exists

- name: Pull app changes
  git:
    repo: "git@github.com:{{ GITHUB_REPO }}.git"
    dest: "{{ APP_PATH }}"
    single_branch: yes
    version: main
